CHECK_INTERVAL_MS = 30
BRIGHTNESS_THRESHOLD = 0.90
CONFIG_FILE = "window_choice.json"
ENABLE_CANCEL_BUTTON = False
FALSE_POSITIVE_CHECK_SEC = 1
SOLID_DURATION = 2.0
FADE_DURATION = 2.0

assert CHECK_INTERVAL_MS > 0
assert 0.0 <= BRIGHTNESS_THRESHOLD <= 1.0
assert len(CONFIG_FILE) > 0
assert SOLID_DURATION >= 0.0
assert FADE_DURATION >= 0.0
